Integration tests
kinecosystem/kin-core-android pull request #14
Opened 2018-02-04 12:53 UTC by yosriz

add integration tests on real horizon test net
* make wipeout method work (add clearAllAccount in KeyStore) for integration tests
* fix some bugs with KeyStore 
* mark all network dependant long running tests as @LargeTest
* skip those tests in travis build

2018-02-08 08:12 UTC, OrenZak commented on .travis.yml
> +  - adb shell am instrument -w -e notAnnotation android.support.test.filters.LargeTest  kin.sdk.core.test/android.support.test.runner.AndroidJUnitRunner
add comments?

2018-02-08 08:14 UTC, OrenZak commented on dependencies.gradle
> +            hamcrest   : buildDependency(hamcrestPackage, 'hamcrest-library', hamcrestVersion)
format

2018-02-08 08:15 UTC, OrenZak commented on kin-sdk-core/build.gradle
> +    implementation 'com.github.kinfoundation:android-stellar-sdk:support_below_api19-SNAPSHOT'
move to `dependencies.gradle`

2018-02-08 08:22 UTC, OrenZak commented on kin-sdk-core/src/androidTest/java/kin/sdk/core/FakeKinIssuer.java
> +    private static final String KIN_ISSUER_SEED = "SDL34EFTWFPIVJLUYSCVZJFYPYLIGFHDYG5VKOVBQYLU6H4OWRPETCAE";
let's generate it in the code every time.

2018-02-08 08:24 UTC, OrenZak commented on kin-sdk-core/src/androidTest/java/kin/sdk/core/FakeKinIssuer.java
> +    private static final String TEST_NETWORK_URL = "https://horizon-testnet.stellar.org";
we can divide to scheme and base path

2018-02-08 08:24 UTC, OrenZak commented on kin-sdk-core/src/androidTest/java/kin/sdk/core/FakeKinIssuer.java
> +            .host("horizon-testnet.stellar.org")
use the consts

2018-02-08 08:26 UTC, OrenZak commented on kin-sdk-core/src/androidTest/java/kin/sdk/core/FakeKinIssuer.java
> +        assertTrue(response != null && response.body() != null);
check error code

2018-02-08 08:28 UTC, OrenZak commented on kin-sdk-core/src/androidTest/java/kin/sdk/core/FakeKinIssuer.java
> +    private final Asset asset;
rename to kinAsset

2018-02-08 09:34 UTC, OrenZak commented on kin-sdk-core/src/main/java/kin/sdk/core/KinClient.java
> +        if (getAccountsCount() > index) {
check index < 0

2018-02-08 09:45 UTC, OrenZak commented on kin-sdk-core/src/test/java/kin/sdk/core/KinClientTest.java
> +        kinClient = new KinClient(mockClientWrapper);
check if we can init in setUp

2018-02-08 09:46 UTC, OrenZak commented on kin-sdk-core/src/test/java/kin/sdk/core/KinClientTest.java
> +        KinAccount kinAccount = kinClient.addAccount("123456");
use `PASSPHRASE` const

2018-02-08 09:51 UTC, OrenZak commented on kin-sdk-core/src/test/java/kin/sdk/core/KinClientTest.java
> +        kinClient = new KinClient(mockClientWrapper);
please check also for the count.

2018-02-08 09:56 UTC, OrenZak commented on kin-sdk-core/src/androidTest/java/kin/sdk/core/KinAccountIntegrationTest.java
> +    }
Maybe add @after and wipeoutAccount

2018-02-08 10:07 UTC, OrenZak requested changes
Good job !!!!! see the comments :)

2018-02-08 14:50 UTC, yosriz commented
@OrenZak Thanks, changes applied, also for https://github.com/kinfoundation/kin-sdk-core-stellar-android/pull/13, please approve :smile:

2018-02-11 07:58 UTC, OrenZak commented
👍 Great work !! thanks !

2018-02-11 10:28 UTC, OrenZak approved these changes

2018-02-11 10:51 UTC, merged