Feature/transaction history
kinecosystem/kin-core-android pull request #53
Opened 2018-10-14 13:21 UTC by drEfrati

Payments History Feature

2018-10-14 14:09 UTC, mrsegev approved these changes
Nice, just make the changes we talked about + update Readme file to reflect the new API.

2018-10-14 18:57 UTC, yosriz commented on kin-core/src/main/java/kin/core/AccountInfoRetriever.java
> +    void setBlockChainEvents(BlockchainEvents blockchainEvents) {
To be consistent with the current design - every dependency should be "injected" directly into the ctor (and then omit the null checks)

2018-10-14 19:00 UTC, yosriz commented on kin-core/src/main/java/kin/core/BlockchainEvents.java
> +    PaymentInfo getPaymentInfo(TransactionResponse transactionResponse) {
extract seems like a more appropriate name

2018-10-14 19:36 UTC, yosriz requested changes
:+1:
The most important comments are regarding the public APIs (the ability to change account id, the token)
Regarding tests, please see codecov report:
https://codecov.io/gh/kinecosystem/kin-core-android/commit/2534f9f47b3c99f2df00420ae8f1ddc117b28be4 
I'm not sure why codecov didn't put a comment on the PR like it does always (maybe you need to sign in?)

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/AccountInfoRetriever.java
> +    private BlockchainEvents blockchainEvents;
can you extract the `TransactionResponse` -> `PaymentInfo` logic to a common class? it's not entirely clean to have ` AccountInfoRetriever` depends on unrelated `BlockchainEvents` class

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/AccountInfoRetriever.java
> +            Page<TransactionResponse> execute = transactions
execute -> response

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/AccountInfoRetriever.java
> +                throw new AccountNotActivatedException(accountId);
why it's `AccountNotActivatedException` in this case?
what does null response mean? I would expect general exception (data cannot be retrieved) like in getBalance/sendTransaction

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/AccountInfoRetriever.java
> +            e.printStackTrace();
rethrow this as `OperationFailedException`

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/BlockchainEvents.java
> +        // return a new payment info object if possible, otherwise return null.
seems a redundant comment

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/KinAccount.java
> +     * Create {@link Request} for getting all the transactions payments history for the current account.
payment transactions

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/KinAccount.java
> +     * @return {@code Request<List<PaymentInfo>> } PaymentInfo - the payment information for a specific payment operation in a transaction
List of

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/KinAccount.java
> +     * Create {@link Request} for getting all the transactions payments history for a given account.
I don't think we should expose the possibility of giving an account id, as it doesn't match the current interfaces - `KinAccount` is for a specific address and it doesn't appropriate to give an option here to query other accounts.

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/KinAccount.java
> +     * <p><b>cursor:</b>   is optional, a paging token, specifying where to start returning records from. for example 12884905984.</p>
I'm not sure how token can be used here? what actually it is?
We should give the option to get this token from every payment o.w. it is not useful currently

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/KinAccount.java
> +     * Get the list of the transactions payments history for the current account.
limit doc - maybe something like: default limit is 10, use `getPaymentsHistorySync(PaymentsHistoryRequestParams)` for providing a differnt limit

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/KinAccountImpl.java
> +        String accountId = requestParams.getAccountId();
see comment above regarding specifying account id

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/PaymentsHistoryRequestParams.java
> + * Class which build optional params for the transaction payment history request.
Represents optional params for payment history request, see <add link to the method>

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/PaymentsHistoryRequestParams.java
> +    protected PaymentsHistoryRequestParams(Parcel in) {
why does it need to be parcelable?

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/PaymentsHistoryRequestParams.java
> +    public static class PaymentsHistoryRequestParamsBuilder {
just Builder (`new PaymentsHistoryRequestParams.Builder`)

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/PaymentsHistoryRequestParams.java
> +        public PaymentsHistoryRequestParamsBuilder account(String accountId) {
add "set" prefix to be consistent with other builders

2018-10-14 19:36 UTC, yosriz commented on kin-core/src/main/java/kin/core/PaymentsHistoryRequestParams.java
> +        public PaymentsHistoryRequestParamsBuilder account(String accountId) {
add docs for setters

2018-10-16 05:16 UTC, yosriz commented on kin-core/src/main/java/kin/core/KinAccount.java
> +     * The default is currently the last 10 payments, please use use {@link KinAccount#getPaymentsHistory((PaymentsHistoryRequestParams)} for providing a different limit.
"currently" is redundant, a suggestion: "The default limit is 10 payments".

2018-10-16 05:16 UTC, yosriz commented on kin-core/src/main/java/kin/core/KinAccount.java
> +     * The default is currently the last 10 payments, please use use {@link KinAccount#getPaymentsHistory((PaymentsHistoryRequestParams)} for providing a different limit.
redundant "use" (please use use)

2018-10-16 05:16 UTC, yosriz commented on kin-core/src/main/java/kin/core/KinAccount.java
> +     * @return {@code Request<List<PaymentInfo>> } PaymentInfo - the payment information for a specific payment operation in a transaction
the return value doc should specify it is the list of payments of this account.

2018-10-16 05:18 UTC, yosriz commented on kin-core/src/main/java/kin/core/PaymentInfoHelper.java
> +public class PaymentInfoHelper {
should internal class with all the methods internal as well

2018-10-16 05:19 UTC, yosriz commented on kin-core/src/main/java/kin/core/PaymentsHistoryRequestParams.java
> +//        /**
dead code comment - should be deleted

2018-10-16 05:21 UTC, yosriz reviewed
@drEfrati I've added small comments for small tweaks, other than that it's all good

2019-05-13 14:41 UTC, closed without merging